#ifndef BARCODEPROCESSING_GLOBAL_H
#define BARCODEPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BARCODEPROCESSING_LIBRARY)
#  define BARCODEPROCESSING_EXPORT Q_DECL_EXPORT
#else
#  define BARCODEPROCESSING_EXPORT Q_DECL_IMPORT
#endif

#endif // BARCODEPROCESSING_GLOBAL_H
