#ifndef CAMERACONNECTION_GLOBAL_H
#define CAMERACONNECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAMERACONNECTION_LIBRARY)
#  define CAMERACONNECTION_EXPORT Q_DECL_EXPORT
#else
#  define CAMERACONNECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERACONNECTION_GLOBAL_H
